### ISSUE TITLE
Requesting comment on relative code freshness

### ISSUE THREAD

**Issue by Intensity** [dorssel/dotnet-xmss#59]
Given the additional XMSS implementation here: https://github.com/FoxCryptoNL/xmss-library

I'm wondering if this current repository is considered more up-to-date, as in getting attention, bugfixes, and so on. Perhaps the other, C-based, library omits XMSS^MT and that may be the main difference apart from the underlying language.

**Comment by dorssel** [comment]
Answered in private conversation.
